"""fix_relationship_names

Revision ID: 4a7fa210e6fb
Revises: 251137c8c0b9
Create Date: 2025-12-18 15:16:35.211135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7fa210e6fb'
down_revision: Union[str, Sequence[str], None] = '251137c8c0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centros_treinamento', 'endereco')
    op.drop_column('centros_treinamento', 'proprietario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('proprietario', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('centros_treinamento', sa.Column('endereco', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
